### ISSUE TITLE
WONDER-726 JPEG code in ERAttachment will need re-write to compile with Java 1.7

### ISSUE THREAD

**Issue by pascalrobert** [wocommunity/wonder#85]
Reported by Ray Kiddy

The problem is below. I tried taking the ERAttachment component out to test the rest of the build, but too many things have the ERAttachment framework on their dependencies list. Does BTBusinessLogic desperately need the ERAttachment framework? It must. O well. 

[wocompile] Compiling 38 source files to /Users/ray/Roots/classes/ERAttachment 
[wocompile] warning: [options] bootstrap class path not set in conjunction with -source 1.5 
[wocompile] /Users/ray/Projects/wonder/Frameworks/BusinessLogic/ERAttachment/Sources/er/attachment/metadata/DrewMetadataParser.java:23: error: cannot access JPEGDecodeParam 
[wocompile] Metadata metadata = JpegMetadataReader.readMetadata(importFile); 
[wocompile] ^ 
[wocompile] class file for com.sun.image.codec.jpeg.JPEGDecodeParam not found 

The com.sun.image.codec.jpeg.JPEGDecodeParam class does not seem to be available to Java 1.7. Is the javax.imageio.plugins.jpeg.JPEGImageReadParam the class that this will be migrating to? It is not clear. The API of the JPEGImageReadParam class is not exactly comparable. 

Or is there a way to have the com.sun.image.codec.jpeg.JPEGDecodeParam used by the Java 1.7 compiler when we build the ERAttachment framework?
